# Generated by Django 4.2.3 on 2023-08-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activesubscriptions',
            table='active_subcriptions',
        ),
        migrations.AlterModelTable(
            name='paymentdetails',
            table='payment_details',
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subcription',
        ),
    ]
