# Generated by Django 4.2.3 on 2023-08-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_activesubscriptions_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activesubscriptions',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentdetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subscription',
            table=None,
        ),
    ]
