# Generated by Django 4.2.3 on 2023-08-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddresses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('coordinates', models.JSONField()),
                ('type', models.CharField(max_length=255)),
                ('created_on', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modified_on', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('login_status', models.BooleanField(default=False)),
                ('created_on', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modified_on', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
