# Generated by Django 4.2.3 on 2023-08-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1000)),
                ('logo', models.CharField(max_length=1000)),
                ('email_id', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=255)),
                ('db_id', models.IntegerField()),
                ('created_on', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.BigIntegerField()),
                ('modified_on', models.BigIntegerField()),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_charge', models.FloatField()),
                ('earning_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOutlets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outlet_id', models.IntegerField()),
                ('outlet_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(max_length=100)),
                ('created_on', models.BigIntegerField()),
                ('modified_on', models.BigIntegerField()),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OutletBrandsLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outlet_id', models.IntegerField()),
                ('brand_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outlets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('outlet_type', models.IntegerField()),
                ('schema_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1000)),
                ('logo', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=200)),
                ('fssai', models.CharField(max_length=1000)),
                ('gst', models.CharField(max_length=1000)),
                ('trade_license', models.CharField(max_length=1000)),
                ('primary', models.BooleanField()),
                ('bank_details', models.JSONField()),
                ('created_on', models.CharField(max_length=100)),
                ('modified_on', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceableLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCompanyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_id', models.CharField(max_length=255)),
            ],
        ),
    ]
