# Generated by Django 4.2.3 on 2023-08-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('variant_id', models.IntegerField()),
                ('addon_variants', models.JSONField()),
                ('created_on', models.BigIntegerField()),
                ('modified_on', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponCodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('coupon_type', models.CharField(max_length=255)),
                ('percentage_off', models.IntegerField()),
                ('amount_off', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('minimum_total', models.IntegerField()),
                ('excluded_categories', models.JSONField()),
                ('cap', models.IntegerField()),
                ('customer_specific', models.JSONField()),
                ('item_id', models.JSONField()),
                ('created_on', models.BigIntegerField()),
                ('expiry_on', models.BigIntegerField()),
                ('brand_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponOutletLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_id', models.IntegerField()),
                ('outlet_id', models.IntegerField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponOutletLinkValidatior',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('coupon_id', models.IntegerField()),
                ('outlet_id', models.IntegerField()),
                ('visible', models.BooleanField()),
            ],
            options={
                'db_table': 'coupon_outlet_connection',
            },
        ),
        migrations.CreateModel(
            name='CustomerCuponUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_id', models.IntegerField()),
                ('customer_phone', models.CharField(max_length=255)),
                ('used_amount', models.IntegerField()),
                ('used_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerCouponCodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_id', models.IntegerField()),
                ('cut', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
