# Generated by Django 4.2.3 on 2023-08-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_table_alter_couponcodes_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='couponcodes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='couponoutletlink',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customercuponusage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='influencercouponcodes',
            table=None,
        ),
    ]
