# Generated by Django 4.2.3 on 2023-08-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAmountTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_addition', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyOutletCheckout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('created_on', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DECheckout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('de_id', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('submitted_on', models.BigIntegerField()),
                ('created_on', models.BigIntegerField()),
                ('modified_on', models.BigIntegerField()),
                ('can_edit', models.BooleanField(default=False)),
                ('submitted_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orders_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DECheckoutWithAmount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('de_checkout_id', models.IntegerField()),
                ('checkout_amount_id', models.IntegerField()),
                ('total_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryExecutives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('de_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(max_length=20)),
                ('dob', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('bank_details', models.JSONField()),
                ('aadhar_no', models.IntegerField()),
                ('aadhar_photo', models.CharField(max_length=1000)),
                ('dl_photo', models.CharField(max_length=1000)),
                ('dl_expiry_date', models.BigIntegerField()),
                ('emission_expiry_date', models.BigIntegerField()),
                ('emission_photo', models.CharField(max_length=1000)),
                ('insurance_photo', models.CharField(max_length=1000)),
                ('insurance_expiry_date', models.BigIntegerField()),
                ('vehicle_photo', models.CharField(max_length=1000)),
                ('de_photo', models.CharField(max_length=1000)),
                ('rc_photo', models.CharField(max_length=1000)),
                ('device_type', models.CharField(max_length=255)),
                ('esign', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.BigIntegerField()),
                ('modified_on', models.BigIntegerField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earning_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.BigIntegerField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('module_id', models.IntegerField()),
                ('create', models.BooleanField()),
                ('read', models.BooleanField()),
                ('update', models.BooleanField()),
                ('delete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.IntegerField()),
                ('created_on', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCompanyLink',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('outlet_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('outlet_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('created_on', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modified_on', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('loggedin_details', models.JSONField()),
            ],
        ),
    ]
