# Generated by Django 4.2.3 on 2023-08-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('FIXED', 'FIXED'), ('PERCENTAGE', 'PERCENTAGE')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('TAX', 'TAX'), ('ADDITIONAL_CHARGE', 'ADDITIONAL_CHARGE')], max_length=50)),
                ('target', models.CharField(choices=[('ITEMS', 'ITEMS'), ('DELIVERY_CHARGE', 'DELIVERY_CHARGE'), ('TOTAL', 'TOTAL')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('brand_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item_variant_name', models.CharField(max_length=255)),
                ('addon_variants', models.JSONField()),
                ('addons_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('brand_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderOnlinePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('payment_data', models.JSONField()),
                ('status', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=100)),
                ('payment_service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_id', models.IntegerField()),
                ('order_status', models.CharField(max_length=100)),
                ('epoch_time', models.BigIntegerField()),
                ('created_on', models.BigIntegerField()),
                ('modified_on', models.BigIntegerField()),
                ('pre_order_time', models.BigIntegerField()),
                ('de_id', models.IntegerField()),
                ('location', models.JSONField()),
                ('delivery_type_id', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(max_length=20)),
                ('address_id', models.IntegerField()),
                ('coupon_id', models.IntegerField()),
                ('coupon_details', models.JSONField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip', models.IntegerField()),
                ('additional_charges', models.JSONField()),
                ('contactless', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(max_length=255)),
                ('platform_details', models.JSONField()),
                ('visible', models.BooleanField(default=True)),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('invoice_id', models.IntegerField()),
                ('third_party_service_id', models.IntegerField(help_text='This is used for storing third party service id')),
                ('third_party_service_type', models.BooleanField(default=False, help_text='This is used for toggling external delivery executives for the order')),
                ('order_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersEdited',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('orders', models.JSONField()),
                ('items', models.JSONField()),
                ('created_on', models.BigIntegerField()),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('order', models.JSONField()),
                ('status', models.IntegerField()),
                ('created_on', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('type_id', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('review', models.TextField()),
                ('photos', models.JSONField()),
                ('created_on', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField()),
                ('web_active', models.BooleanField()),
                ('web_message', models.CharField(max_length=255)),
                ('app_active', models.BooleanField()),
                ('app_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OutletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=50)),
                ('setting_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.outlet')),
            ],
        ),
    ]
